name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Install playwright browsers
        run: yarn test:install-deps

      - name: Run tests
        run: yarn test:ci
